argo_namespace: argocd

config:
  helmRepositories:
    - name: private-helm-repo
      url: https://private.repo/
      usernameSecret:
        name: secret_name
        key: key_name
      passwordSecret:
        name: secret_name
        key: key_name
    - name: incubator
      url: https://kubernetes-charts-incubator.storage.googleapis.com/
  repositories:
    - url: repo_url
      sshPrivateKeySecret: #the chart doesn't install the secert
        name: secret_name
        key: key_name

rbac:
# See https://github.com/argoproj/argo-cd/blob/master/docs/rbac.md on how to write RBAC policies.
# This will effacte on all argocd instances
  policyCsv: |
    g, role_name, role:admin
  policyDefault: role:readonly

projects:
    - name: project_name
      destinations:
        - namespaces: [namespace]
          #server: https://kubernetes.default.svc
      description: description
      sourceRepos:
      - 'repo_url'
      #clusterResourceWhitelist:
      #- group: '*'
      #  kind: '*'
      roles:
      - name: role_name
        description: role_description
        oidcGroups: [' grop_name']
        policies: |

        jwtTokens:
        - iat: 123
