config:
  url: https://argocd_url
  #idcConfig:
  #  name: Okta
  #  clientID:
  #  clientSecret:
  #  issuer:

applications:
  - name: app_name
    project: project
    destination:
      namespace: namespace
    git:
      url: url
      branch: branch
      path: path #path to the value file
    value_files:
    - values-staging.yaml
