apiVersion: batch/v1
kind: Job
metadata:
  generateName: after-
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sleep", "30"]
      restartPolicy: Never
  backoffLimit: 4
