apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: {{ .Values.argo_namespace}}
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ include "argo-cd.name" . }}
data:
  url: {{ .Values.config.url }}
{{- if .Values.config.helmRepositories }}
  helm.repositories: |
{{ toYaml .Values.config.helmRepositories | indent 4 }}
{{- end }}
{{- if .Values.config.repositories }}
  repositories: |
{{ toYaml .Values.config.repositories | indent 4 }}
{{- end }}
{{- if .Values.config.oidcConfig }}
  oidc.config: |
{{ toYaml .Values.config.oidcConfig | indent 4 }}
{{- end }}
