{{- $namespace := .Values.argo_namespace -}}
{{- $chart_name := include "argo-cd.name" . -}}
{{- $chart := include "argo-cd.chart" . -}}

{{- range .Values.projects }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: {{ $namespace }}
labels:
  app.kubernetes.io/name: {{ $chart_name }}
  helm.sh/chart: {{ $chart }}
  app.kubernetes.io/instance: {{ $.Release.Name }}
  app.kubernetes.io/managed-by: {{ $.Release.Service }}
  app.kubernetes.io/part-of: {{ $chart_name }}
spec:
  description: {{ .description }}
  sourceRepos:
  {{ toYaml .sourceRepos | indent 2 -}}
  destinations:
  {{- range .destinations }}
  - namespace: {{ .namespaces }}
    server: {{.server | default "https://kubernetes.default.svc" }}
  {{- end }}

  {{-  if .clusterResourceWhitelist  }}
  clusterResourceWhitelist:
{{ toYaml .clusterResourceWhitelist| indent 2 }}
  {{-  end }}

  roles:
  {{- range .roles }}
  - name: {{ .name }}
    description: {{ .description }}
    policies:
{{ toYaml .policies| indent 6 }}
    jwtTokens:
{{ toYaml .jwtTokens| indent 6 }}
    groups:
{{ toYaml .oidcGroups| indent 6 -}}
  {{-  end }}

---
{{- end }}
